version: '2'
services:
  keycloak-db:
    image: postgres:13
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak


  keycloak:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - keycloak-db
    ports:
      - "80:8080"
    environment: 
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
